# Generated by Django 4.2.6 on 2023-11-10 09:45

import api.product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=api.product.models.upload_to),
        ),
    ]
