# Generated by Django 5.0 on 2024-01-21 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
